// Generated by CoffeeScript 1.3.3
(function() {

  $.ajax({
    type: 'POST',
    url: '/rpc',
    data: {
      method: 'ls',
      args: ['pdfjs/pdfs']
    },
    dataType: 'json',
    success: function(pdfs) {
      var basename, html, list, pdf, _i, _len, _results;
      list = $('#list');
      _results = [];
      for (_i = 0, _len = pdfs.length; _i < _len; _i++) {
        pdf = pdfs[_i];
        basename = pdf.basename;
        html = "<li><a href=\"reader.html#" + basename + "\">" + basename + "</a></li>";
        _results.push(list.append(html));
      }
      return _results;
    }
  });

}).call(this);
