// Generated by CoffeeScript 1.3.3
(function() {
  var PORT, app, express, log, shell;

  PORT = process.env.PORT || 5000;

  log = console.log;

  express = require('express');

  shell = require('./lib/shell');

  app = express().use(express["static"](__dirname + '/apps')).use(express.bodyParser());

  app.get('/', function(req, res) {
    return res.redirect('/default');
  });

  app.post('/rpc', function(req, res) {
    var args, method, _ref;
    _ref = req.body, method = _ref.method, args = _ref.args;
    return shell[method](args, function(data) {
      return res.json(data);
    });
  });

  app.listen(PORT, function() {
    return log("listening on port " + PORT);
  });

}).call(this);
