// Generated by CoffeeScript 1.3.3
(function() {
  var PORT, app, express, log;

  PORT = process.env.PORT || 5000;

  log = console.log;

  express = require('express');

  app = express().use(express["static"](__dirname + '/app'));

  app.listen(PORT, function() {
    return log("listening on port " + PORT);
  });

}).call(this);
