// Generated by CoffeeScript 1.3.3
(function() {
  var log, rpc;

  log = console.log.bind(console);

  rpc = function(method, args, success) {
    return $.ajax({
      type: 'POST',
      url: '/rpc',
      data: {
        method: method,
        args: args
      },
      dataType: 'json',
      success: success
    });
  };

  rpc('ls', ['.'], function(files) {
    var basename, file, list, _i, _len, _results;
    list = $('#list');
    _results = [];
    for (_i = 0, _len = files.length; _i < _len; _i++) {
      file = files[_i];
      basename = file.basename;
      _results.push(list.append("<li><a href=\"/" + basename + "\">" + basename + "</a></li>"));
    }
    return _results;
  });

}).call(this);
