// Generated by CoffeeScript 1.3.3
(function() {
  var fs, log;

  log = console.log;

  fs = require('fs');

  module.exports = {
    env: function(key) {
      return process.env[key];
    },
    ls: function(path) {
      var basename, files, _i, _len, _ref;
      files = [];
      _ref = fs.readdirSync(path);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        basename = _ref[_i];
        files.push({
          basename: basename
        });
      }
      return files;
    }
  };

}).call(this);
