// Generated by CoffeeScript 1.3.3
(function() {
  var App, Column, Columns, Dir, DirView, File, FileView, Header, app, columns, header, log;

  log = console.log.bind(console);

  File = Backbone.Model.extend({
    defaults: {
      active: false
    }
  });

  FileView = Backbone.View.extend({
    tagName: 'li',
    template: JST.file,
    render: function() {
      this.$el.addClass(this.model.get('type'));
      this.$el.html(this.template(this.model.toJSON()));
      return this;
    },
    initialize: function() {
      return this.model.on('change:active', this.active, this);
    },
    active: function(active) {
      return this.$el.toggleClass('active', active);
    }
  });

  Dir = Backbone.Collection.extend({
    model: File
  });

  DirView = Backbone.View.extend({
    tagName: 'ul',
    initialize: function() {
      return this.collection.on('reset', this.render, this);
    },
    render: function() {
      var _this = this;
      this.collection.each(function(file) {
        var fileView;
        fileView = new FileView({
          model: file
        });
        return _this.$el.append(fileView.render().el);
      });
      this.collection.at(0).set('active', true);
      return this;
    }
  });

  Column = Backbone.View.extend();

  Columns = Backbone.View.extend({
    initialize: function() {
      return this.model.on('change:pwd', this.append, this);
    },
    append: function(app, pwd) {
      var _this = this;
      return app.rpc('ls', [pwd], function(files) {
        var dir, dirView;
        dir = new Dir(files);
        dirView = new DirView({
          collection: dir
        });
        return _this.$el.append(dirView.render().el);
      });
    }
  });

  Header = Backbone.View.extend({
    template: JST.header,
    render: function() {
      this.$el.html(this.template(this.model.toJSON()));
      return this;
    },
    initialize: function() {
      return this.model.on('change:pwd', this.render, this);
    }
  });

  App = Backbone.Model.extend({
    rpc: function(method, args, cb) {
      return $.ajax({
        type: 'POST',
        url: '/rpc',
        data: {
          method: method,
          args: args
        },
        dataType: 'json',
        success: cb
      });
    }
  });

  app = new App;

  header = new Header({
    model: app,
    el: '#header'
  });

  columns = new Columns({
    model: app,
    el: '#columns'
  });

  app.rpc('env', ['HOME', 'USER', 'HOSTNAME'], function(data) {
    var hostname, pwd, user;
    pwd = data[0], user = data[1], hostname = data[2];
    return app.set({
      pwd: pwd,
      user: user,
      hostname: hostname
    });
  });

}).call(this);
